const supabaseUrl = 'https://zmtrkjsuyhdbjtiefcqj.supabase.co';
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptdHJranN1eWhkYmp0aWVmY3FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYzNDEwODAsImV4cCI6MjA5MTkxNzA4MH0.lBDgNXXtpKbrqeeXCRZ6_sMFyCQOGySLiZs_t_8RxWc';

export const client = supabase.createClient(supabaseUrl, supabaseKey);